<?xml version="1.0" encoding="ISO-8859-1"?>
<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
             xmlns:tns="urn:arnleadservicewsdl"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             targetNamespace="urn:VisitorServiceWsdl">

    <types>
        <xsd:schema targetNamespace="urn:Visitor">
            <xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/" />
            <xsd:import namespace="http://schemas.xmlsoap.org/wsdl/" />
        </xsd:schema>
    </types>

    <message name="VisitorCreateRequest">
        <part name="name" type="xsd:string" />
    </message>

    <message name="VisitorCreateResponse">
        <part name="return" type="xsd:string" />
    </message>

    <portType name="VisitorPortType">
        <operation name="VisitorCreate">
            <documentation>Visitor: Create</documentation>
            <input message="tns:VisitorCreateRequest"/>
            <output message="tns:VisitorCreateResponse"/>
        </operation>
    </portType>

    <binding name="VisitorBinding" type="tns:VisitorPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="VisitorCreate">
            <soap:operation soapAction="urn:arnleadservicewsdl#VisitorCreate" style="rpc"/>

            <input>
                <soap:body use="encoded" namespace="urn:VisitorCreateRequest"
                           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </input>

            <output>
                <soap:body use="encoded" namespace="urn:VisitorCreateResponse"
                           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </output>
        </operation>
    </binding>

    <service name="Visitor">
        <port name="VisitorPort" binding="tns:VisitorBinding">
            <soap:address location="http:/10.3.51.21/api/v1/webservice" />
        </port>
    </service>
</definitions>